Fix PoseidonConstants `serde` Implementation
lurk-lab/neptune pull request #184
Opened 2023-05-20 01:49 UTC by winston-h-zhang

Addresses https://github.com/lurk-lab/lurk-rs/issues/401.

From @huitseeker's insight, the manual implementation had some alignment issues. The solution was to directly `#[derive(Serialize, Deserialize)]` for `PoseidonConstants`, as well as add the `#[serde(bound)]` to generate a correct implementation.

2023-05-20 02:20 UTC, porcuquine approved these changes

2023-05-20 03:12 UTC, huitseeker reviewed
Re:CI, see https://github.com/lurk-lab/lurk-rs/pull/356

2023-05-20 03:12 UTC, huitseeker commented on Cargo.toml
> +bincode = "1.3.3"
It seems you should be able to add bincode only to dev-dependencies

2023-05-22 13:48 UTC, huitseeker approved these changes

2023-05-22 13:54 UTC, huitseeker requested changes, later dismissed

2023-05-22 13:54 UTC, huitseeker commented on src/serde_impl.rs
> -    }
Actually, on the plus side: we have bincode tests! 
On the minus side: we lost serde_json tests!

2023-05-22 14:13 UTC, huitseeker commented
(the request for changes, here, is because the serde impl breaks serde_json tests)

2023-05-22 15:20 UTC, huitseeker commented on src/serde_impl.rs
> -"];
This was the original issue with the fields in this custom impl, BTW. Note the double quotes, the slice of length 1, and how this is declaring a single-field struct.

2023-05-22 17:38 UTC, huitseeker commented on src/poseidon.rs
> +        h1.set_preimage(&preimage); // reset
🤦 hahaha, got it, thanks for the fix

2023-05-22 17:38 UTC, huitseeker approved these changes
Thanks a lot! I've checked the generated code is the same as the original, except for correcting the originally-mangled FIELDS constant.

2023-05-22 17:42 UTC, winston-h-zhang commented
On `Nova`, I'm running into a very strange error:
```rust
running 1 test
thread 'provider::poseidon::tests::test_serde_roundtrip_what' panicked at 'called `Result::unwrap()` on an `Err` value: 
Custom("invalid value: integer `6`, expected variant index 0 <= i < 6")', src/provider/poseidon.rs:291:84
```

Looking around, I found https://github.com/bincode-org/bincode/issues/424, so it seems like using `serde(skip)` is unstable. I'm not sure why, but the roundtrip tests pass on Neptune and fail on Nova... I've been banging my head on this for the past hour to no avail. In any case, we may have to revert back to Sam's custom implementation.

2023-05-22 19:21 UTC, winston-h-zhang commented
Ok, with this, we should finally be out of the thorns @huitseeker @samuelburnham!

2023-05-22 22:58 UTC, huitseeker requested changes, later dismissed
While I accepted a previous version, I think this version misses a few of the forced field implementations of the original (Deserialize for Poseidon constants). I've tried to comment online in the deleted impl where we lose behavior wrt the current. 
I would suggest:
- for round_constants, instead of serde_skip, we use [default](https://serde.rs/field-attrs.html#default)
- for the other fields, we can probably define them with [serde_with](https://serde.rs/field-attrs.html#with), though in aggregate, it may be easier to reuse the existing custom impl, and correct it's FIELDS constant?

2023-05-22 22:58 UTC, huitseeker commented on src/hash_type.rs
> +#[doc(hidden)]
Why?

2023-05-22 22:58 UTC, huitseeker commented on src/hash_type.rs
> +    // #[serde(skip)] // See: https://github.com/bincode-org/bincode/issues/424
Let's not leave this comment here since we have resolved this otherwise

2023-05-22 22:58 UTC, huitseeker commented on src/serde_impl.rs
> -                    domain_tag: hash_type.domain_tag(),
This line is valuable

2023-05-22 22:58 UTC, huitseeker commented on src/serde_impl.rs
> -                    half_full_rounds: full_rounds / 2,
This line is valuable

2023-05-22 22:58 UTC, huitseeker commented on src/serde_impl.rs
> -                    domain_tag: hash_type.domain_tag(),
This is valuable

2023-05-22 22:58 UTC, huitseeker commented on src/serde_impl.rs
> -                    half_full_rounds: full_rounds / 2,
This is valuable

2023-05-22 22:58 UTC, huitseeker commented on src/serde_impl.rs
> -                    round_constants: None,
This is valuable

2023-05-22 22:58 UTC, huitseeker commented on src/serde_impl.rs
> -                    round_constants: None,
This is valuable

2023-05-22 23:06 UTC, winston-h-zhang commented
Ok, maybe it's best to just restore @samuelburnham's original impl, then

2023-05-23 00:39 UTC, huitseeker approved these changes
Thanks a lot @winston-h-zhang !

2023-05-23 00:42 UTC, samuelburnham approved these changes

2023-05-23 01:36 UTC, merged