Unsafe Serialization for Poseidon Constants
lurk-lab/neptune pull request #194
Opened 2023-06-12 17:10 UTC by winston-h-zhang

This PR implements the `Abomonation` traits necessary for the upstream of faster public parameter caching in Nova. See https://github.com/lurk-lab/lurk-rs/pull/399 for details.

2023-06-13 19:05 UTC, huitseeker reviewed
This needs https://github.com/lurk-lab/bellperson/commit/71930b5b5e98763a3337e61365c213b23d7d79f6 i.e. https://github.com/lurk-lab/bellperson/pull/3 for CI to pass, otherwise LGTM.

2023-06-14 19:13 UTC, huitseeker requested changes
This needs a rebase!

2023-06-14 19:13 UTC, huitseeker commented on Cargo.toml
> +abomonation_derive = { git = "https://github.com/winston-h-zhang/abomonation_derive.git" }
Do you have a PR opened upstream to extend this, since IIUC it's a strict improvement over the proc-macro therein?

2023-06-14 19:15 UTC, winston-h-zhang commented on Cargo.toml
> +abomonation_derive = { git = "https://github.com/winston-h-zhang/abomonation_derive.git" }
I don't think `abomonation_derive` is maintained anymore. I could open a PR, but we will have to withhold the expectation of it getting anywhere

2023-06-14 23:57 UTC, huitseeker commented on Cargo.toml
> +abomonation_derive = { git = "https://github.com/winston-h-zhang/abomonation_derive.git" }
Fine by me: the reason we do all this is poor expectations.

2023-06-14 23:58 UTC, huitseeker approved these changes
Thanks a bunch!

2023-06-15 00:11 UTC, merged