ci: use resuable workflows
lurk-lab/neptune pull request #255
Opened 2023-12-21 23:17 UTC by huitseeker

2023-12-21 23:25 UTC, huitseeker commented
Hmm, I forgot to remove the part of the test that runs the doctests, which makes the failure of https://github.com/lurk-lab/neptune/actions/runs/7294189991/job/19878612122?pr=255 weird.

2023-12-22 00:30 UTC, huitseeker commented
This is the line that makes this tricky, reduced the PR to something simpler for now:
https://github.com/lurk-lab/neptune/blob/main/gbench/Cargo.toml#L25

2023-12-22 01:45 UTC, samuelburnham requested changes

2023-12-22 01:45 UTC, samuelburnham commented on .github/workflows/rust.yml
> +      - uses: ./.github/actions/ci-env
We can also use the `gpu-setup` action to cut down on more lines in both the `cuda` and `opencl` jobs

2023-12-22 01:45 UTC, samuelburnham commented on .github/workflows/rust.yml
> +  # Lint dependencies for licensing and auditing issues as per https://github.com/lurk-lab/arecibo/blob/main/deny.toml
```suggestion
  # Lint dependencies for licensing and auditing issues as per https://github.com/lurk-lab/neptune/blob/main/deny.toml
```

2023-12-22 13:50 UTC, huitseeker commented
Pausing work on this: we need to switch to https://github.com/dtolnay/rust-toolchain first, before we use our reusable workflows.

2023-12-23 16:46 UTC, huitseeker commented on .github/workflows/rust.yml
> +      - uses: ./.github/actions/ci-env
That's definitely the next step!

2023-12-23 20:38 UTC, samuelburnham approved these changes

2023-12-23 21:03 UTC, merged